branches:
  only:
    - 5.8-umc
sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
env:
- PIPELINE5_VERSION=5.8-umc.$TRAVIS_BUILD_NUMBER
cache:
  directories:
    - $HOME/.m2
before_script:
  - export GCLOUD_PROJECT=hmf-pipeline-development
  - export GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/deploy/key.json
script:
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then mvn clean deploy -B; else mvn clean install -DskipDocker -DskipShade -B; fi'
before_install:
  - openssl aes-256-cbc -K $encrypted_965d6303826d_key -iv $encrypted_965d6303826d_iv
    -in cluster/src/test/resources/smoke_test/api.jks.enc -out cluster/src/test/resources/smoke_test/api.jks -d
  - openssl aes-256-cbc -K $encrypted_ec9457022768_key -iv $encrypted_ec9457022768_iv
    -in cluster/google-key.json.enc -out cluster/google-key.json -d
  - openssl aes-256-cbc -K $encrypted_e6c508956cde_key -iv $encrypted_e6c508956cde_iv
    -in cluster/google-archive-key.json.enc -out cluster/google-archive-key.json -d
  - openssl aes-256-cbc -K $encrypted_c66cc0a4b32e_key -iv $encrypted_c66cc0a4b32e_iv
    -in deploy/key.json.enc -out deploy/key.json -d

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "hartwigmedicalfoundation" --password-stdin
  - mvn versions:set -DnewVersion=$PIPELINE5_VERSION
  - sudo apt-get -qq update
  - sudo apt-get install -y samtools google-cloud-sdk
  - curl https://downloads.rclone.org/v1.48.0/rclone-v1.48.0-linux-amd64.deb --output rclone-current-linux-amd64.deb
  - sudo dpkg -i rclone-current-linux-amd64.deb
install: "/bin/true"
after_success:
  - docker push hartwigmedicalfoundation/pipeline5:$PIPELINE5_VERSION
  - docker push hartwigmedicalfoundation/batch5:$PIPELINE5_VERSION
